In [1]:
!pip install pandas

In [2]:
!pip install numpy

In [3]:
!pip install seaborn

     ---------------------------------------- 0.0/162.8 kB ? eta -:--:--
     ------ ------------------------------ 30.7/162.8 kB 660.6 kB/s eta 0:00:01
     --------------------------------- ---- 143.4/162.8 kB 1.7 MB/s eta 0:00:01
     -------------------------------------- 162.8/162.8 kB 1.2 MB/s eta 0:00:00
   ---------------------------------------- 0.0/294.9 kB ? eta -:--:--
   ------------------------------ --------- 225.3/294.9 kB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 294.9/294.9 kB 3.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.7 MB ? eta -:--:--
   - -------------------------------------- 0.2/7.7 MB 6.3 MB/s eta 0:00:02
   -- ------------------------------------- 0.5/7.7 MB 6.6 MB/s eta 0:00:02
   --- ------------------------------------ 0.6/7.7 MB 5.7 MB/s eta 0:00:02
   ----- ---------------------------------- 1.1/7.7 MB 6.2 MB/s eta 0:00:02
   ------ --------------------------------- 1.3/7.7 MB 5.6 MB/s eta 0:00:02
   ----

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns

In [6]:
ogr_vize = np.random.randint(40,100,(10))
ogr_vize

array([73, 87, 85, 86, 60, 46, 82, 73, 64, 61])

In [8]:
ogr_final = np.random.randint(40,100,(10))
ogr_final

array([42, 87, 69, 96, 75, 54, 52, 42, 45, 75])

In [14]:
ogr_no = np.random.randint(21000000,22000000,(10))
ogr_no

array([21991743, 21521310, 21249081, 21727827, 21820809, 21331269,
       21085370, 21393793, 21526742, 21884942])

In [15]:
my_def = pd.DataFrame({"ogr_not": ogr_no,"ogr_vize":ogr_vize,"ogr_final":ogr_final}) 
my_def

ogr_not  ogr_vize  ogr_final
0  21991743        73         42
1  21521310        87         87
2  21249081        85         69
3  21727827        86         96
4  21820809        60         75
5  21331269        46         54
6  21085370        82         52
7  21393793        73         42
8  21526742        64         45
9  21884942        61         75

In [16]:
#verilere erişim ,bir sayısal index ile erişim.

In [17]:
my_def.iloc[:5]

ogr_not  ogr_vize  ogr_final
0  21991743        73         42
1  21521310        87         87
2  21249081        85         69
3  21727827        86         96
4  21820809        60         75

In [18]:
my_def.loc[:5]

ogr_not  ogr_vize  ogr_final
0  21991743        73         42
1  21521310        87         87
2  21249081        85         69
3  21727827        86         96
4  21820809        60         75
5  21331269        46         54

In [19]:
#iloc = int bazlı indexleme yapar
#loc = str bazlı indexleme yapar

In [20]:
my_def.index

RangeIndex(start=0, stop=10, step=1)

In [21]:
my_def.index = ["öğrenci 1","öğrenci 2","öğrenci 3","öğrenci 4","öğrenci 5","öğrenci 6","öğrenci 7","öğrenci 8","öğrenci 9","öğrenci 10",]
my_def

ogr_not  ogr_vize  ogr_final
öğrenci 1   21991743        73         42
öğrenci 2   21521310        87         87
öğrenci 3   21249081        85         69
öğrenci 4   21727827        86         96
öğrenci 5   21820809        60         75
öğrenci 6   21331269        46         54
öğrenci 7   21085370        82         52
öğrenci 8   21393793        73         42
öğrenci 9   21526742        64         45
öğrenci 10  21884942        61         75

In [22]:
#dataframe de bir sütuna ait verinin değerine erişim sağlamak için.

In [23]:
my_def['ogr_final'].values

array([42, 87, 69, 96, 75, 54, 52, 42, 45, 75])

In [24]:
my_def["ogr_bolum"] = "YBS"
my_def

ogr_not  ogr_vize  ogr_final ogr_bolum
öğrenci 1   21991743        73         42       YBS
öğrenci 2   21521310        87         87       YBS
öğrenci 3   21249081        85         69       YBS
öğrenci 4   21727827        86         96       YBS
öğrenci 5   21820809        60         75       YBS
öğrenci 6   21331269        46         54       YBS
öğrenci 7   21085370        82         52       YBS
öğrenci 8   21393793        73         42       YBS
öğrenci 9   21526742        64         45       YBS
öğrenci 10  21884942        61         75       YBS

In [25]:
#ogr_ortalama isimli bir sütun ekleyin bu sütundaki değerler ogr_vize nin yüzde 40 ı ile final in yüzde 60 ını toplamı olacak.

In [26]:
vize = my_def["ogr_vize"].values

In [27]:
vize

array([73, 87, 85, 86, 60, 46, 82, 73, 64, 61])

In [28]:
final = my_def["ogr_final"].values
final

array([42, 87, 69, 96, 75, 54, 52, 42, 45, 75])

In [29]:
my_ort = (vize*0.4)+(final*0.6)

In [30]:
my_def["ogr_ortalama"] = my_ort
my_def

ogr_not  ogr_vize  ogr_final ogr_bolum  ogr_ortalama
öğrenci 1   21991743        73         42       YBS          54.4
öğrenci 2   21521310        87         87       YBS          87.0
öğrenci 3   21249081        85         69       YBS          75.4
öğrenci 4   21727827        86         96       YBS          92.0
öğrenci 5   21820809        60         75       YBS          69.0
öğrenci 6   21331269        46         54       YBS          50.8
öğrenci 7   21085370        82         52       YBS          64.0
öğrenci 8   21393793        73         42       YBS          54.4
öğrenci 9   21526742        64         45       YBS          52.6
öğrenci 10  21884942        61         75       YBS          69.4

In [37]:
ortalama = my_def["ogr_ortalama"].values
ortalama

array([54.4, 87. , 75.4, 92. , 69. , 50.8, 64. , 54.4, 52.6, 69.4])

In [40]:
my_def["Durum"] = my_def["ogr_ortalama"] > 65
my_def


ogr_not  ogr_vize  ogr_final ogr_bolum  ogr_ortalama  Durum
öğrenci 1   21991743        73         42       YBS          54.4  False
öğrenci 2   21521310        87         87       YBS          87.0   True
öğrenci 3   21249081        85         69       YBS          75.4   True
öğrenci 4   21727827        86         96       YBS          92.0   True
öğrenci 5   21820809        60         75       YBS          69.0   True
öğrenci 6   21331269        46         54       YBS          50.8  False
öğrenci 7   21085370        82         52       YBS          64.0  False
öğrenci 8   21393793        73         42       YBS          54.4  False
öğrenci 9   21526742        64         45       YBS          52.6  False
öğrenci 10  21884942        61         75       YBS          69.4   True

In [41]:
my_df2 = sns.load_dataset("titanic")

In [42]:
#pandas da elimizdeki veriseti hakkında bilgimiz yoksa
#describe()
#info()

In [43]:
my_df2.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [44]:
my_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [45]:
my_df2.shape

(891, 15)

In [46]:
my_df2.size

13365

In [48]:
my_df2.pivot_table("survived",index="sex",columns="class")

C:\Users\Lab1-\AppData\Local\Temp\ipykernel_11972\3546283825.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  my_df2.pivot_table("survived",index="sex",columns="class")


class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [49]:
my_df2["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [50]:
my_df2.pivot_table("survived",index="age",columns="class")

C:\Users\Lab1-\AppData\Local\Temp\ipykernel_11972\878600007.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  my_df2.pivot_table("survived",index="age",columns="class")


class  First  Second  Third
age                        
0.42     NaN     NaN    1.0
0.67     NaN     1.0    NaN
0.75     NaN     NaN    1.0
0.83     NaN     1.0    NaN
0.92     1.0     NaN    NaN
...      ...     ...    ...
70.00    0.0     0.0    NaN
70.50    NaN     NaN    0.0
71.00    0.0     NaN    NaN
74.00    NaN     NaN    0.0
80.00    1.0     NaN    NaN

[88 rows x 3 columns]

In [51]:
#pivot_table karşılaştırmalar yapmak için kullanılır.

In [53]:
my_df2.pivot_table("survived",index="sex",columns="pclass",aggfunc="sum")

pclass   1   2   3
sex               
female  91  70  72
male    45  17  47

In [55]:
my_df2.groupby("sex")["age"].mean()

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [56]:
my_df2.groupby(["survived","sex"])["age"].mean()

survived  sex   
0         female    25.046875
          male      31.618056
1         female    28.847716
          male      27.276022
Name: age, dtype: float64

In [58]:
my_def3 = my_df2.pivot_table("survived",index="sex",columns="pclass",aggfunc="sum")
my_def3

pclass   1   2   3
sex               
female  91  70  72
male    45  17  47

In [59]:
?pd.DataFrame.to_excel

Signature:
pd.DataFrame.to_excel(
    self,
    excel_writer: 'FilePath | WriteExcelBuffer | ExcelWriter',
    *,
    sheet_name: 'str' = 'Sheet1',
    na_rep: 'str' = '',
    float_format: 'str | None' = None,
    columns: 'Sequence[Hashable] | None' = None,
    header: 'Sequence[Hashable] | bool_t' = True,
    index: 'bool_t' = True,
    index_label: 'IndexLabel | None' = None,
    startrow: 'int' = 0,
    startcol: 'int' = 0,
    engine: "Literal['openpyxl', 'xlsxwriter'] | None" = None,
    merge_cells: 'bool_t' = True,
    inf_rep: 'str' = 'inf',
    freeze_panes: 'tuple[int, int] | None' = None,
    storage_options: 'StorageOptions | None' = None,
    engine_kwargs: 'dict[str, Any] | None' = None,
) -> 'None'
Docstring:
Write object to an Excel sheet.

To write a single object to an Excel .xlsx file it is only necessary to
specify a target file name. To write to multiple sheets it is necessary to
create an `ExcelWriter` object with a target file name, and specify a sheet
in the f

In [60]:
!pip install openpyxl

   ---------------------------------------- 0.0/250.0 kB ? eta -:--:--
   --- ----------------------------------- 20.5/250.0 kB 640.0 kB/s eta 0:00:01
   ------------- -------------------------- 81.9/250.0 kB 1.1 MB/s eta 0:00:01
   ------------------------------------ --- 225.3/250.0 kB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 250.0/250.0 kB 1.7 MB/s eta 0:00:00


In [62]:
pd.DataFrame.to_excel(my_def3,"deneme.xlsx")
#bu verileri deneme isimli excel tablosunda görebilirim bu kod ile.

In [63]:
my_arr1 = np.random.randint(10,50,(5))
my_arr2 = np.random.randint(10,50,(5))


In [67]:
my_dizi_ismi = ["Ahmet","Mehmet","Furkan","Saadet","Nur"]
my_dict = {"İsim": my_dizi_ismi,"yas":my_arr1}
my_dict2 = {"İsim": my_dizi_ismi,"yas":my_arr2}

my_df_1 = pd.DataFrame.from_dict(my_dict)
my_df_2 = pd.DataFrame.from_dict(my_dict2)

In [68]:
my_df_1

İsim  yas
0   Ahmet   27
1  Mehmet   21
2  Furkan   47
3  Saadet   23
4     Nur   47

In [69]:
my_df_2

İsim  yas
0   Ahmet   31
1  Mehmet   38
2  Furkan   10
3  Saadet   39
4     Nur   43

In [73]:
my_df_3 = pd.concat([my_df_1,my_df_2])
my_df_3

İsim  yas
0   Ahmet   27
1  Mehmet   21
2  Furkan   47
3  Saadet   23
4     Nur   47
0   Ahmet   31
1  Mehmet   38
2  Furkan   10
3  Saadet   39
4     Nur   43
0   Ahmet   31
1  Mehmet   38
2  Furkan   10
3  Saadet   39
4     Nur   43

In [75]:
my_df_4 = pd.merge(my_df_1,my_df_2)
my_df_4

İsim  yas
0   Ahmet   31
1  Mehmet   38
2  Furkan   10
3  Saadet   39
4     Nur   43